### ISSUE TITLE
D3JSv6 passive listener type-error while drag inside the chart(used zoom event)?

### ISSUE THREAD

**Issue by MUTHUKUMAR73737** [d3/d3-zoom#232] opened 2021-03-26 10:13 UTC
![image](https://user-images.githubusercontent.com/37654694/112616497-d27b8800-8e49-11eb-8ed4-6cc337cd1414.png)

I am getting above error in the browser console when I drag(zoom - mousemove event is calling) inside the chart.

`d3.select("svg") 
.call( d3.zoom() .scaleExtent([1, 10]) 
.translateExtent([[0, 0], [400, 215]]) 
.extent([[0, 0], [400, 215]]) 
.on("zoom", function (event) { // stuff here })
`
I am using d3js version 6.3.1 inside angular application. 

Please help me to resolve this issue.

**Comment by Fil** [comment] 2021-03-26 10:18
Duplicate of https://github.com/d3/d3-zoom/issues/231

**Closed by Fil** 2021-03-26 10:18 UTC
