### ISSUE TITLE
function scale in Transform should support kX and kY instead of k

### ISSUE THREAD

**Issue by DywiTom** [d3/d3-zoom#267] opened 2023-05-31 10:47 UTC
Hello!

I saw that the function scale in Transform doesn't support X and Y.
See more here in the in the [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale).

Thanks!

**Comment by Fil** [comment] 2023-05-31 12:12
Duplicate of #48

**Closed** 2023-05-31 12:12 UTC
