### ISSUE TITLE
Zoom event does not honor current transform state

### ISSUE THREAD

**Issue by ashwinmr** [d3/d3-zoom#238] opened 2021-06-20 06:00 UTC
I was trying to maintain my own transform state and update it incrementally with zoom events. This was so that I can maintain a history of zoom states and switch between them (go back and next). 

I was hoping to use the zoom event similar to the `scaleBy` and `translateBy` functions. This requires resetting the transform for the node at the end of each event. However, I noticed that when the event is fired again, the transform contained in `e.transform` does not care about the existing transform of the node. It gives a transform that keeps growing larger and larger.

I asked a question on [here](https://stackoverflow.com/questions/67959261/how-to-store-zoom-state-and-update-incrementally-in-d3) on stackoverflow. The answer works but is quite hacky. 

Can the zoom event be made to honor the current zoom transform? Can the transform be reset without firing an event and creating an infinite loop?

**Comment by Fil** [comment] 2021-06-21 08:01
Closing since I think it works as expected; however if you think this is a bug, please share minimal code that allows reproduction of the issue.

**Closed by Fil** 2021-06-21 08:01 UTC
