### ISSUE TITLE
Zoomable DOM conflict(Angular & D3JS)

### ISSUE THREAD

**Issue by MUTHUKUMAR73737** [d3/d3-zoom#233] opened 2021-04-01 12:01 UTC
I have implemented vertical bar chart with zoom feature using d3js(inside angular(version - 7.0.1) application).

When I drag inside the chart I am getting below error.

![2021-04-01 17_15_31-Window](https://user-images.githubusercontent.com/37654694/113289865-6c41aa00-930e-11eb-8609-dcd2ffb49076.png)

Sample chart in stackblitz(Working without type-error):
[https://stackblitz.com/edit/angular-7-zoomable-bar-chart](url)

The above issue is not occurring in the sample app(please see above link).

In angular application when I remove window click event. The above type-error is not occurring even when we drag inside the chart(please see below screenshot)

![2021-04-01 17_14_51-Window](https://user-images.githubusercontent.com/37654694/113290509-626c7680-930f-11eb-956c-381f15a20f72.png)

The error file in angular application is given below as screenshot.

![2021-04-01 17_12_46-Window](https://user-images.githubusercontent.com/37654694/113290638-8cbe3400-930f-11eb-8019-d50cb4a1cced.png)

Please help me to resolve this issue.

Thanks in anticipation.

**Comment by Fil** [comment] 2021-04-01 16:18
Hello, this is a duplicate of https://github.com/d3/d3-zoom/issues/231

**Closed by Fil** 2021-04-01 16:18 UTC

**Comment by MUTHUKUMAR73737** [comment] 2021-04-08 04:07
Above issue is resolved by doing code change in the d3-drag(**nodrag.js**) file.

![drag-issue](https://user-images.githubusercontent.com/37654694/113966711-3be99680-984d-11eb-9a0f-fd3678a3f2ac.png)

What I changed(Making event listener option as false) in my node modules nodrag.js file is 
`selection.on("click.drag", noevent, false)`

I knew the above approach is not a correct option to do. 

Please help to resolve this issue.

Thanks in anticipation.
