### ISSUE TITLE
Erratic click handling

### ISSUE THREAD

**Issue by vwochnik** [d3/d3-zoom#81] opened 2017-01-04 12:16 UTC
Consider the use of `d3-zoom` in combination with a click handler. The zoom is called on the SVG and manipulates a `g`'s `transform` attribute. There is an element that responds to a click.

The problem is that not every click is being processed. See [this minimal example][1]. Move the mouse a little between clicks. You will see that the circle is not pulsing for every click which it should. Without `d3-zoom`, there is no problem. However, for me, if I do not move the mouse between clicks, everything is fine.

[1]: https://bl.ocks.org/vwochnik/231e58acd2f7bff4b096d1f1f971f22a

**Comment by mbostock** [comment] 2017-01-04 15:53
Duplicate of #65.

**Closed by mbostock** 2017-01-04 15:53 UTC

**Comment by vwochnik** [comment] 2017-01-04 15:54
Well, OK. I have tried capturing `mousedown`, `mousemove` and `mouseup` and haven't captured a `mousemove` after the `mousedown` but maybe they have been stopped by the zoom behavior.
