### ISSUE TITLE
Click event not triggered 

### ISSUE THREAD

**Issue by xuzb** [d3/d3-zoom#77] opened 2016-12-13 09:07 UTC
Hi,

I was trying to use d3-zoom to draw a zoomable graph with nodes and edges.

A node can be selected when it is clicked and also can be deselected when the zoomable background is clicked.

The problem here is that a mouse move event is fired along with a mouse down event in chrome 

(windows 10, chrome version is 52.0. The following link describes the problem:
https://bugs.chromium.org/p/chromium/issues/detail?id=161464
)

So the click event on the zoomble background will not be triggered as it enables drag event, which results in that the selected status on node cannot be cancelled.

**Comment by mbostock** [comment] 2016-12-13 15:33
Duplicate of #65.

**Closed by mbostock** 2016-12-13 15:33 UTC
