### ISSUE TITLE
No wheel sourceEvent on 'end' event

### ISSUE THREAD

**Issue by mathieucivel** [d3/d3-zoom#68] opened 2016-10-27 11:19 UTC
When binding an `end` event, looking at the event `sourveEvent`, I correctly get an `MouseEvent` when panning, but no `WheelEvent` when zooming with the wheel (in fact a mac touchpad). 

Is this the intended behaviour ?

I would like to differentiate between the end of a programatic zoom and the end of a user zoom. In order to move on, I created my own debounced `zoom` event but its not the cleanest way.

**Comment by mbostock** [comment] 2016-10-27 19:19
This is the expected behavior. The browser (and operating system) does not provide any concept of a wheeling gesture, so there’s no explicit way to tell when a wheeling gesture starts and ends. As noted on the table of events in the [API Reference](https://github.com/d3/d3-zoom#api-reference), the behavior of d3-zoom is to treat a wheeling gesture as ended if no wheel event is received for 150ms. Thus, the source event of the end event is undefined when wheeling.

I suppose we could change it to treat the last wheel event as the source event of the timeout, but that’s a little weird because it would be well after the source event has expired. Maybe it could make a CustomEvent, but that feels a little weird too.

It might be more reliable to rely on the sourceEvent on start, rather than on end.

**Comment by mbostock** [comment] 2016-10-27 19:20
(I’m not immediately planning on changing this behavior, so I’m closing this issue, but reply here and we can keep discussing it.)

**Closed by mbostock** 2016-10-27 19:20 UTC

**Comment by mathieucivel** [comment] 2016-10-28 05:34
I understand, thank you for your answer. It seems that, for this use case, making a custom weird end event on the code that use d3-zoom is better then.

If it can help someone, here is the code I used:

```js
import debounce from 'lodash/debounce';
import {event} from 'd3-selection';
import {zoom} from 'd3-zoom';

const debouncedZoomEnd = debounce(onCustomZoomEnd, 150);
let zoom = zoom().on('zoom.end', () => {
  let type = event && event.sourceEvent && event.sourceEvent.type;
  debouncedZoomEnd(type);
})

function onCustomZoomEnd(type) {
  //...
}
```
