### ISSUE TITLE
Does not receive "end" event after pressing right mouse button during drag & drop with left button

### ISSUE THREAD

**Issue by kapulkin** [d3/d3-zoom#198] opened 2019-12-29 21:52 UTC
I bind brush tool to zoom events with left mouse button. Also I bind drag & drop logic to zoom events with right button pressed. You could look here: https://viete.io/a170102c-e7b6-11e9-b4f9-9600001cf28e

To reproduce:
1. Open https://viete.io/a170102c-e7b6-11e9-b4f9-9600001cf28e
2. Start make selection by moving mouse on white space with left button pressed.
3. Don't release mouse left button and press right button additionally
4. Release right button and move mouse with left button pressed little more.
5. Release mouse left button. 
6. Zoom **end** or **start** events will not occur anymore. And selection and drag & drop functionality become broken.

![2019-12-30_00-46-05](https://user-images.githubusercontent.com/800129/71563303-4cce2880-2a9e-11ea-9e28-7b5659d51300.png)

I use code below to initialize zoom:

```
  async mounted () {
    const self = this

    select(this.selectionToolSelector)
      .call(
        this.zoomTool = zoom()
          .scaleExtent([1 / 20, 5])
          .filter(() => { return !event.ctrlKey })
          .on('start', self.zoomStart)
          .on('zoom', self.zoomed)
          .on('end', self.zoomEnd)
          // TODO: listen zoom on end to open contextMenu
      )

```

I use nuxt and d3 of versions:
"nuxt": "^2.9.2"
"d3": "^5.11.0"

**Comment by kapulkin** [comment] 2019-12-29 23:10
Look, please, for pull request #199 with a possible fix for the issue.

**Comment by kapulkin** [comment] 2019-12-30 18:30
I applied already my fork https://github.com/kapulkin/d3-zoom at https://viete.io/a170102c-e7b6-11e9-b4f9-9600001cf28e, so you will not be able to reproduce the bug there.

**Comment by SilverIrbis** [comment] 2020-03-20 08:21
Hi!
Excuse me, may I ask, how do you rebind buttons for dragging on the mouse and combine it with the brush? I have a similar ask now, but Im new at d3 and kinda stuck with it

**Comment by Fil** [comment] 2020-05-29 10:06
I'm sorry I'm not able to reproduce the issue. Could you try and isolate it in a simple page (a block or notebook?).

I'm also surprised that `.filter(() => { return !event.ctrlKey })` works, as variable `event` doesn't appear to be defined.

To read the mouse buttons and filter the zoom start accordingly, you might want to test d3.event.buttons (https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons).

**Comment by kapulkin** [comment] 2020-05-31 22:04
1. Look, please, on suggested change in pull request. The fix really improve logic, so it is acceptable to merge the pull request

2. I import d3.event as event, that, why the code works.

**Comment by Fil** [comment] 2020-06-01 12:44
It would really help to be able to reproduce the issue with readable code. I've spent quite some time on it now, but I wasn't able to figure out how to make the gesture's "active" count go beyond 1. I can only suppose that there is a conflict between event listeners.

Also, I don't dispute that your patch helps in your case, and that it makes sense to unregister mouseup only if the active count is down to 0, but I'm not sure why we would unregister mousemove.zoom and restore drag in that case? If the gesture has somehow not been closed by that mouseup event, then everything should wait for the real end of the gesture?

**Comment by amannn** [comment] 2020-09-02 10:39
I'm not sure if this is related, but I'm having issues with the `mouseup` event not being handled correctly.

![chart](https://user-images.githubusercontent.com/4038316/91970354-d0b86e80-ed17-11ea-9e60-ab25ec3c888d.gif)

There's a zoom applied to the chart and when I'm dragging in the context area below, the `mouseup` doesn't seem to end the pan gesture. The `mousemove` events that happen after `mouseup` cause the chart to be panned again. Once I pan the regular chart above, the panning stops correctly.

This behaviour happend after an upgrade to `d3-zoom@2.0.0`.

Here's a reproduction: https://codepen.io/amann/pen/QWNqdqw?editors=1010. Sorry that the example is a bit convoluted. I'm new to d3 and wasn't sure which parts I could safely remove.

**Comment by Fil** [comment] 2020-09-02 13:01
@amannn I'm promoting your question to its own separate issue in https://github.com/d3/d3-zoom/issues/222

**Comment by amannn** [comment] 2020-09-02 13:04
@Fil Thank you for your help!

**Closed** 2021-06-10 00:02 UTC
