### ISSUE TITLE
iPhone Performance issues since iOS 16

### ISSUE THREAD

**Issue by pavodev** [d3/d3-zoom#265] opened 2023-04-05 09:19 UTC
Hello,

I'm developing an interactive graph and I noticed that it has really bad performance on iPhones since the iOS 16 update. The lag occurs noticeably more when the graph is zoomed in, did anyone notice any performance issues related to zoom/pan?

You can check out my web app on this https://course-glancer.netlify.app/glancer/square

**Comment by Fil** [comment] 2023-05-31 12:13
duplicate of #266

**Closed by Fil** 2023-05-31 12:13 UTC
