### ISSUE TITLE
Option to disable double-click and double-tap behavior

### ISSUE THREAD

**Issue by vwochnik** [d3/d3-zoom#49] opened 2016-08-12 06:52 UTC
I require `d3-zoom` to not zoom in on a double-click or double-tap since it is interfering with my use case. The use case is as follows: Given a graph, the zoom behavior is programmatically changed when the user clicks on a node in such a way that the node appears on the center of the screen. When clicked on the background, the zoom is reset.

**Comment by mbostock** [comment] 2016-08-12 17:43
You can disable double-click by removing the dblclick.zoom event listener after applying the zoom behavior:

```js
selection
    .call(zoom)
    .on("dblclick.zoom", null);
```

Unfortunately, there’s not a similarly easy way to disable the double-tap because this is a “synthetic” event caused by a single-touch touchstart quickly following another single-touch touchstart.

Are you still allowing wheel-based zooming and multi-touch zooming? Or are you only allowing zooming by tapping on nodes or the background? In the later case you could simply avoid applying the zoom behavior to the selection, and simply use it programmatically via *zoom*.transform.

**Comment by vwochnik** [comment] 2016-08-15 12:41
Well, what you mentioned is exactly the point why I have opened this issue. The synthetic behavior is contained inside `d3-zoom`. Therefore, it would make sense to have an option to disable the behavior entirely.

**Comment by mbostock** [comment] 2016-08-15 16:40
Yes; if you there were an easy way to accomplish the requested feature without modifying d3-zoom, I would have already closed this issue. Currently the only way to disable double-tap would be to fork d3-zoom or to only use d3-zoom programmatically, handling input events yourself can then calling *zoom*.transform as desired.

**Closed** 2016-08-27 18:32 UTC

**Comment by vwochnik** [comment] 2016-08-30 06:58
Many thanks to you @mbostock!

**Comment by envision** [comment] 2017-01-26 23:04
@mbostock how do you disable these events with this demo? As it is not calling on selection.

http://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172

Or actually what I would like to implement, rather than disabling, is to undo zooming with double-click. And after that animation has finished, to call a custom function (to resample datasets).

**Comment by 452701513** [comment] 2018-12-05 03:43
there is no dblclick property d.3 v3
